#!/usr/bin/env bash
set -euo pipefail
WS="/home/kavia/workspace/code-generation/simple-to-do-list-35140-35150/backend"
mkdir -p "$WS" && cd "$WS"
# ensure python3 venv module available
if ! python3 -c "import venv" >/dev/null 2>&1; then sudo apt-get update -q && sudo apt-get install -y -q python3-venv >/dev/null; fi
# create venv idempotently; if broken, recreate
if [ ! -d "$WS/.venv" ]; then python3 -m venv "$WS/.venv"; fi
. "$WS"/.venv/bin/activate
# verify venv python/pip
VE_PY="$WS/.venv/bin/python"
VE_PIP="$WS/.venv/bin/pip"
if [ "$(readlink -f "$(which python)")" != "$(readlink -f "$VE_PY")" ]; then echo "Activated python is not workspace venv python" >&2; exit 20; fi
# upgrade pip/setuptools/wheel
"$VE_PY" -m pip install --upgrade pip setuptools wheel --quiet >/dev/null
# write local .env for non-login scripts
DEV_SECRET="dev-secret-key-please-change"
DEV_DEBUG="True"
cat > "$WS/.env" <<'ENV'
DJANGO_DEBUG='True'
DJANGO_SECRET_KEY='dev-secret-key-please-change'
ENV
# persist globally for login shells via /etc/profile.d
sudo tee /etc/profile.d/dev_django.sh >/dev/null <<'EOF'
# Development Django environment (autogenerated)
export DJANGO_DEBUG='True'
export DJANGO_SECRET_KEY='dev-secret-key-please-change'
EOF
sudo chmod 644 /etc/profile.d/dev_django.sh
# export into current process for immediate use
export DJANGO_DEBUG="$DEV_DEBUG"
export DJANGO_SECRET_KEY="$DEV_SECRET"
# quick sanity check
"$VE_PY" -c "import sys; print('py',sys.version.split()[0])" >/dev/null
